name: TwoMove CI - Django Tests & Auto Merge

on:
  push:
    branches: [ "pruebas" ]
  pull_request:
    branches: [ "pruebas" ]

jobs:
  build:
    name: Ejecutar tests Django
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Instalar driver ODBC para SQL Server
        run: |
          sudo su
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
          exit
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar entorno Django
        run: |
          echo "DJANGO_SETTINGS_MODULE=TwoMove.settings" >> $GITHUB_ENV
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=sk_test_fake123" >> $GITHUB_ENV
          echo "STRIPE_PUBLIC_KEY=pk_test_fake123" >> $GITHUB_ENV
          echo "DEFAULT_FROM_EMAIL=noreply@twomove.co" >> $GITHUB_ENV
          echo "DEBUG=True" >> $GITHUB_ENV
          echo "DB_NAME=TwoMoveDB" >> $GITHUB_ENV
          echo "DB_USER=sa" >> $GITHUB_ENV
          echo "DB_PASSWORD=yourStrong(!)Password" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=1433" >> $GITHUB_ENV

      - name: Aplicar migraciones
        run: |
          python manage.py migrate --noinput

      - name: Ejecutar pruebas unitarias
        run: |
          python manage.py test --verbosity 2

  merge:
    name: Merge automático a main
    needs: build
    runs-on: ubuntu-latest
    if: success()

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Hacer merge automático de pruebas a main
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: pruebas
          target_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
